name: Bug Report | Bug 反馈
description: Create a report to help us improve | 创建一个报告来帮助我们改进
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!  
        感谢您抽出时间填写此 Bug 报告！  

        ⚠️ Note  
        Bug fixes are usually handled from simple to complex, and we cannot guarantee that your issue belongs to the simple category.  
        If the problem description is unclear or lacks necessary context, troubleshooting and fixing it later will be much more difficult, or even impossible to reproduce.  
        Therefore, please provide as much detail as possible, including **the observed behavior, steps to reproduce, and your environment information**, to help us resolve the issue faster.  

        ⚠️ 注意  
        Bug 的修复通常会按照从易到难的顺序进行，我们无法保证您的问题属于简单范畴。  
        如果问题描述不够清晰、缺乏必要的上下文信息，后续排查和修复将会更加困难，甚至可能无法重现。  
        因此，请尽可能提供 **完整的现象描述、复现步骤和环境信息**，以帮助我们更快地解决问题。

  - type: textarea
    attributes:
      label: Describe the bug | 描述错误
      description: A clear and concise description of what the bug is. | 清晰简洁地描述错误是什么。
    validations:
      required: true

  - type: textarea
    attributes:
      label: To Reproduce | 重现步骤
      description: Steps to reproduce the behavior. | 重现该行为的步骤。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior | 预期行为
      description: A clear and concise description of what you expected to happen. | 清晰简洁地描述您期望发生的事情。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots | 截图
      description: If applicable, add screenshots to help explain your problem. | 如果适用，请添加屏幕截图以帮助解释您的问题。

  - type: input
    attributes:
      label: Platform | 平台
      description: The platform you are using. (e.g. Windows 10) | 您使用的平台。
    validations:
      required: true

  - type: input
    attributes:
      label: BDS Version | BDS版本
      description: The version of BDS you are using. (e.g. 1.20.32.1) | 您使用的BDS版本。
    validations:
      required: true

  - type: input
    attributes:
      label: LeviLamina Version | LeviLamina版本
      description: The version of LeviLamina you are using. (e.g. 1.0.0) | 您使用的LeviLamina版本。
    validations:
      required: true

  - type: input
    attributes:
      label: Version | 版本
      description: The version of the PLand you are using. (e.g. 1.0.0) | 您使用的 PLand 版本。
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context | 其他上下文
      description: Add any other context about the problem here. | 在此处添加有关问题的任何其他上下文。
